deployment:
  image:
    repository: ghcr.io/renlabs-dev/prediction-swarm-dash

  podLabels:
    app: prediction-swarm-dash

  env:
    JWT_SECRET:
      valueFrom:
        secretKeyRef:
          name: "torus-{{ .Values.environmentName }}-web-apps-secret"
          key: jwt_secret
    POSTGRES_URL:
      valueFrom:
        secretKeyRef:
          name: "torus-{{ .Values.environmentName }}-web-apps-secret"
          key: torus_prediction_swarm_db_url
    TORUS_WALLET_SEED_PHRASE:
      valueFrom:
        secretKeyRef:
          name: "torus-{{ .Values.environmentName }}-web-apps-secret"
          key: torus_wallet_seed_phrase
    NEXT_PUBLIC_TORUS_ALLOCATOR_ADDRESS:
      valueFrom:
        configMapKeyRef:
          name: '{{ template "application.name" . }}-config'
          key: torus_allocator_address
